---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector

- name: Install nginx & Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse
