---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse

  - src: https://github.com/rizl-ad/lighthouse-role.git
    scm: git
    version: "1.0.0"
    name: lighthouse

  - src: https://github.com/rizl-ad/vector-role.git
    scm: git
    version: "1.1.0"
    name: vector