{
 "title": "Services requests count",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Servece Security total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_total{app=\"security\"}",
     "legendFormat": "metod: {{method}}, status: {{status}}"
    }
   ]
  },
  {
   "title": "Servece Storage total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "minio_s3_requests_total{app=\"storage\"}",
     "legendFormat": "api: {{api}}"
    }
   ]
  },
  {
   "title": "Servece Upload total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_requests_total{app=\"uploader\"}",
     "legendFormat": "method: {{method}}, route: {{route}}, status: {{status}}"
    }
   ]
  }
 ]
}