---
clickhouse:
  hosts:
    clickhouse01:
      ansible_host: "{{ clickhouse01_ip }}"
      ansible_user: "{{ user_name }}"
      ansible_ssh_private_key_file: "{{ ssh_key }}"

vector:
  hosts:
    vector01:
      ansible_host: "{{ vector01_ip }}"
      ansible_user: "{{ user_name }}"
      ansible_ssh_private_key_file: "{{ ssh_key }}"

lighthouse:
  hosts:
    lighthouse01:
      ansible_host: "{{ lighthouse01_ip }}"
      ansible_user: "{{ user_name }}"
      ansible_ssh_private_key_file: "{{ ssh_key }}"
